services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    environment:
      - CADDY_INGRESS_NETWORKS=floodilka-shared
      - CADDY_DOCKER_CADDYFILE_PATH=/config/Caddyfile.base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy_data:/data
      - /srv/frontend:/srv/frontend:ro
    configs:
      - source: caddyfile_stage
        target: /config/Caddyfile.base
    networks:
      - floodilka-shared
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

configs:
  caddyfile_stage:
    file: ./Caddyfile.stage

networks:
  floodilka-shared:
    external: true

volumes:
  caddy_data:
