port 26379
bind 0.0.0.0
protected-mode no
sentinel resolve-hostnames yes

sentinel monitor lk-master 192.168.0.125 6379 3
sentinel auth-pass lk-master ${LIVEKIT_VALKEY_PASSWORD}
sentinel down-after-milliseconds lk-master 5000
sentinel failover-timeout lk-master 10000
sentinel parallel-syncs lk-master 1

requirepass ${LIVEKIT_VALKEY_PASSWORD}

sentinel announce-ip ${NODE_PRIVATE_IP}
sentinel announce-port 26379
