services:
  redirect:
    image: alpine:latest
    command: ["sleep", "infinity"]
    networks:
      - floodilka-shared
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.role == infra
      resources:
        limits:
          cpus: '0.01'
          memory: 8M
      labels:
        caddy: floodilka.ru
        caddy.redir: "https://floodilka.com{uri} permanent"

networks:
  floodilka-shared:
    external: true
